@startuml
!include_once https://raw.githubusercontent.com/chilit-nl/plantuml-event-modeling/main/event-modeling-lib.iuml

$enableAutoAlias()
$enableAutoSpacing()

' Based on https://developer.axoniq.io/w/from-model-to-code-event-modeling-axon-framework
$wireframe(Registration Screen)
$command(Register Account)
$event(Account Registered)

$wireframe(Add Lesson Screen)
$command(Add Lesson)
$event(Lesson Added)

$wireframe(Lesson Selection Screen)
$command(Book Lesson)
$event(Lesson Request Rejected)

$wireframe(Payment Details Screen)
$command(Book Lesson)
$event(Lesson Booked)
$arrow(Payment Details Screen, Pay)
$command(Pay)
$event(Payment Requested)

$wireframe(Payment Approval Screen, $offset = 4)
$command(Process Payment, $offset = 3)
$event(Payment Rejected)
$event(Payment Accepted)
$commandarrow(Process Payment, Payment Accepted)

$wireframe(Lesson Bookings Screen)

$renderEventModelingDiagram()
@enduml